import { PasswordRound } from '@vicons/material';
import { defineTool } from '../tool';
import { translate } from '@/plugins/i18n.plugin';

export const tool = defineTool({
  name: translate('tools.basic-auth-generator.title'),
  path: '/basic-auth-generator',
  description: translate('tools.basic-auth-generator.description'),
  keywords: [
    'basic',
    'auth',
    'generator',
    'username',
    'password',
    'base64',
    'authentication',
    'header',
    'authorization',
    'basic auth',
    'basic authentication',
    'http auth',
    'http basic auth',
    'auth header',
    'authorization header',
    'basic auth generator',
    'auth token',
    'credentials',
    'login header',
    'http authentication',
    'web authentication',
    'api authentication',
    'rest api auth',
    'api security',
    'http header',
    'base64 encode',
    'base64 encoder',
    'credential encoder',
    'auth encoder',
    'basic auth header',
    'www-authenticate',
    'authentication scheme',
    'http credentials',
    'secure login',
    'api credentials',
    'access control',
    'user authentication',
    'password encoding',
    'auth string',
    'basic auth token',
    'http security',
    'web security',
    'api header',
    'request header',
    'auth tool',
    'authentication tool',
    'developer tool',
    'api testing',
    'postman auth',
    'curl auth',
  ],
  component: () => import('./basic-auth-generator.vue'),
  icon: PasswordRound,
});
