import { Code } from '@vicons/tabler';
import { defineTool } from '../tool';
import { translate } from '@/plugins/i18n.plugin';

export const tool = defineTool({
  name: translate('tools.html-entities.title'),
  path: '/html-entities',
  description: translate('tools.html-entities.description'),
  keywords: [
    'html',
    'entities',
    'escape',
    'unescape',
    'special',
    'characters',
    'tags',
    'encode',
    'decode',
    'html escape',
    'html entities encoder',
    'html special characters',
    'escape html',
    'unescape html',
    'html character encoding',
    'ampersand escape',
    'quote escape',
    'less than',
    'greater than',
    'html entity converter',
    'character entity',
    'named entity',
    'numeric entity',
    'html encoding',
    'html decoding',
    'xss prevention',
    'cross-site scripting',
    'sanitize html',
    'html security',
    'web security',
    'text encoding',
    'unicode entities',
    'ascii entities',
    'html symbols',
    'html parser',
    'html formatter',
    'escape xml',
    'xml entities',
    'html validator',
    'entity reference',
    'character reference',
    'html cleaner',
    'safe html',
    'html injection',
    'entity escape tool',
    'html encode online',
    'html decode online',
    'text sanitizer',
    'string escape',
    'web development',
  ],
  component: () => import('./html-entities.vue'),
  icon: Code,
});
