import { DeviceDesktop } from '@vicons/tabler';
import { defineTool } from '../tool';
import { translate } from '@/plugins/i18n.plugin';

export const tool = defineTool({
  name: translate('tools.device-information.title'),
  path: '/device-information',
  description: translate('tools.device-information.description'),
  keywords: [
    'device',
    'information',
    'screen',
    'pixel',
    'ratio',
    'status',
    'data',
    'computer',
    'size',
    'user',
    'agent',
    'device info',
    'browser info',
    'system info',
    'screen resolution',
    'display info',
    'viewport',
    'screen size',
    'pixel ratio',
    'device pixel ratio',
    'user agent string',
    'browser detection',
    'os detection',
    'operating system',
    'platform',
    'device type',
    'mobile detection',
    'desktop detection',
    'tablet detection',
    'browser name',
    'browser version',
    'screen width',
    'screen height',
    'window size',
    'device specs',
    'hardware info',
    'client info',
    'navigator',
    'system details',
    'device fingerprint',
    'browser fingerprint',
    'responsive design',
    'media query',
    'device testing',
    'browser testing',
    'web development',
    'frontend tool',
    'developer tool',
    'device detector',
    'what is my browser',
  ],
  component: () => import('./device-information.vue'),
  icon: DeviceDesktop,
});
