import { Unlink } from '@vicons/tabler';
import { defineTool } from '../tool';
import { translate } from '@/plugins/i18n.plugin';

export const tool = defineTool({
  name: translate('tools.url-parser.title'),
  path: '/url-parser',
  description: translate('tools.url-parser.description'),
  keywords: [
    'url',
    'parser',
    'protocol',
    'origin',
    'params',
    'port',
    'username',
    'password',
    'href',
    'url parser',
    'parse url',
    'url decoder',
    'query string',
    'query parameters',
    'url components',
    'url analyzer',
    'link parser',
    'url breakdown',
    'url parts',
    'hostname',
    'domain',
    'path',
    'hash',
    'fragment',
    'search params',
    'url builder',
    'uri parser',
    'web address',
    'http url',
    'https url',
    'url structure',
    'url dissect',
    'url extractor',
    'url validator',
    'url debugger',
    'link analyzer',
    'query string parser',
    'url tool',
    'web url parser',
    'url decode',
    'parse uri',
    'url splitter',
    'url segments',
    'subdomain',
    'base url',
    'relative url',
    'absolute url',
    'url scheme',
    'network tool',
    'developer tool',
  ],
  component: () => import('./url-parser.vue'),
  icon: Unlink,
});
